from datetime import datetime

from fpdf import FPDF

if __package__:
    from .config import CHALLANS_DIR, ensure_app_dirs
else:
    from config import CHALLANS_DIR, ensure_app_dirs


class ChallanPDF(FPDF):
    def header(self):
        self.set_fill_color(22, 33, 62)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "NexusTrace Warehouse Challan", ln=True, align="C")
        self.ln(4)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(90, 90, 90)
        self.cell(0, 8, f"Generated by NexusTrace | Page {self.page_no()}", align="C")


def _normalize_product_rows(product_rows, final_count):
    rows = []
    for row in product_rows or []:
        name = str(row.get("product_name") or "").strip()
        if not name:
            continue
        rows.append(
            {
                "product_name": name,
                "count": int(row.get("count") or 0),
            }
        )
    if rows:
        return rows
    return [{"product_name": "All Products", "count": int(final_count or 0)}]


def _filter_rows(product_rows, selected_products):
    if not selected_products:
        return product_rows
    selected = {str(item or "").strip().lower() for item in selected_products if str(item or "").strip()}
    if not selected:
        return product_rows
    return [row for row in product_rows if row["product_name"].strip().lower() in selected]


def generate_challan(
    session_id,
    operator_id,
    batch_id,
    timestamp,
    final_count,
    product_rows=None,
    video_path=None,
    selected_products=None,
    output_basename=None,
):
    ensure_app_dirs()

    rows = _normalize_product_rows(product_rows, final_count)
    rows = _filter_rows(rows, selected_products)
    if not rows:
        raise ValueError("No matching products found for challan generation.")

    total_count = sum(int(row["count"]) for row in rows)
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    pdf = ChallanPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Generated At: {now}", ln=True)
    pdf.cell(0, 8, f"Session ID: {session_id}", ln=True)
    pdf.cell(0, 8, f"Operator ID: {operator_id or '-'}", ln=True)
    pdf.cell(0, 8, f"Batch ID: {batch_id or '-'}", ln=True)
    pdf.cell(0, 8, f"Session Timestamp: {timestamp or '-'}", ln=True)
    pdf.cell(0, 8, f"Video Reference: {video_path or '-'}", ln=True)
    pdf.ln(5)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(235, 240, 250)
    pdf.cell(110, 10, "Product Name", border=1, fill=True)
    pdf.cell(40, 10, "Count", border=1, ln=True, fill=True)

    pdf.set_font("Helvetica", "", 11)
    for row in rows:
        pdf.cell(110, 9, row["product_name"], border=1)
        pdf.cell(40, 9, str(int(row["count"])), border=1, ln=True)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(110, 10, "Total", border=1, fill=True)
    pdf.cell(40, 10, str(total_count), border=1, ln=True, fill=True)
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(
        0,
        7,
        "This challan is system-generated and serves as shipment/delivery audit evidence for warehouse operations.",
    )

    if output_basename:
        file_name = output_basename
    elif selected_products:
        token = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        file_name = f"challan_{session_id}_{token}.pdf"
    else:
        file_name = f"challan_{session_id}.pdf"

    path = CHALLANS_DIR / file_name
    pdf.output(str(path))
    return str(path)
